### PR TITLE
Add support for parsing TypeScript

### LINKED ISSUE #9: Add support for parsing TypeScript syntax
Maybe we need to move on from acorn for this, but to enable support for TypeScript controller files in Stimulus LSP we need to be able to parse TypeScript syntax.

https://github.com/marcoroth/stimulus-lsp/issues/18

### PR DESCRIPTION
**Pull request by Zeko369**
TODOs:
- [ ] Change globs / default controller file naming

Closes #9

### CODE REVIEW

**Review by marcoroth — COMMENTED** [review]
Thanks for taking this on @Zeko369!

**Comment by kierangillblueberry** [comment]
@marcoroth does this need additional work before it's mergeable? Happy to help wherever needed.

**Comment by marcoroth** [comment]
@kierangillblueberry thanks for the offer! I'm actually not quite sure what the status is here, but otherwise feel free to take this one as a base so we can get this merged in!

**Comment by marcoroth** [comment]
Closing in favor of https://github.com/marcoroth/stimulus-parser/pull/49

**Pull request closed without merging**
