### PR TITLE
Feat / switch from Acorn to TSQuery (Support TS Parsing)

### PR DESCRIPTION
**Pull request by CharlieIGG**
- Switches parsing from using acorn to using TSQuery in order to support TS Syntax parsing

### CODE REVIEW

**Comment by marcoroth** [comment]
While #49 added support to parse TypeScript code (through `@typescript-eslint/typescript-estree`) it might still be interesting to explore if TSQuery could simply the parser code.

**Comment by CharlieIGG** [comment]
Hey @marcoroth  just to be clear, what advantages would you be looking to gain with it?

**Comment by marcoroth** [comment]
@CharlieIGG I was thinking we might be able to simplify some of the parser logic since you can more easily query for nodes instead of always checking if the node types match.

**Comment by marcoroth** [comment]
I have an upcoming PR that will a bunch of parser logic. Maybe we can figure out then if it makes sense to keep using the `acorn-walk` package or if it could be simplified with TSQuery.

**Comment by marcoroth** [comment]
The PR I was talking about is #66 which is now part of the 0.1.0 release

**Pull request closed without merging**
